# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  generate-gh-page:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: circleci/openjdk:8-jdk
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: "Install graphviz"
          command: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends graphviz
      - run:
          name: "Install npm"
          command: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends npm
      - run:
          name: chmod permissions to gradlew
          command: chmod +x ./gradlew
      - run:
          name: "Generate documents"
          command: ./gradlew asciidoctor
      - run:
          name: "Publish documents"
          command: | 
            chmod +x scripts/publish-docs.sh
            scripts/publish-docs.sh

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - generate-gh-page:
          filters:
            branches:
              only:
                - main
